FROM gradle:jdk17-alpine AS build
WORKDIR /app

COPY build.gradle settings.gradle ./
COPY src src

RUN gradle clean bootJar -x test

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]