version: '3.9'

services:

  core-db:
    image: postgres:15-alpine
    container_name: core-db
    environment:
      - POSTGRES_DB=banking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    networks:
      - banking-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d banking_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service
    depends_on:
      - core-db:
          condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://core-db:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - banking-network

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    container_name: transaction-service
    depends_on:
      - account-service:
          condition: service_healthy
    environment:
      - ACCOUNT_SERVICE_URL=http://account-service:8080
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8081/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - banking-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - account-service:
          condition: service_healthy
      - transaction-service:
          condition: service_healthy
    ports:
      - 80:8080
    restart: unless-stopped
    networks:
      - banking-network
networks:
  banking-network:
    driver: bridge

volumes:
  pgdata:
