spring:
    application:
        name: api-gateway
    cloud:
      gateway:
        server:
          webmvc:
              routes:
                  - id: account-service
                    uri: http://account-service:8080
                    predicates:
                      - Path=/api/v1/accounts/**
                  - id: transaction-service
                    uri: http://transaction-service:8081
                    predicates:
                        - Path=/api/v1/transactions/**

server:
    port: 8080