spring.application.name=user-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
spring.web.error.include-message=always

app.version=1.0.0
app.description=Account Management Service

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.com.devops.demo=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n